cp target/release/bd_cell_id_2_seq ~/sens05_home/bin
cp target/release/bd_get_single_cell ~/sens05_home/bin
cp target/release/check_read_fast_mapper ~/sens05_home/bin
cp target/release/check_read_gene_mapper ~/sens05_home/bin
cp target/release/check_read_genomic_mapper ~/sens05_home/bin
cp target/release/create_gene_mapper_index ~/sens05_home/bin
cp target/release/create_index ~/sens05_home/bin
cp target/release/create_index_te ~/sens05_home/bin
cp target/release/genomic_mapper ~/sens05_home/bin
cp target/release/get_n_cell_reads ~/sens05_home/bin
cp target/release/int_2_seq ~/sens05_home/bin
cp target/release/quantify_rhapsody_multi ~/sens05_home/bin
cp target/release/quantify_rhapsody ~/sens05_home/bin
cp target/release/quantify_gene_mapper ~/sens05_home/bin
cp target/release/split2samples ~/sens05_home/bin
cp target/release/te_analysis ~/sens05_home/bin
